Resolved Issues
SaptarshiSarkar12/Drifty pull request #193
Opened 2023-01-02 06:23 UTC by bharathkalyans

Made changes to the code as requested!

2023-01-02 06:33 UTC, bharathkalyans commented
Hi @SaptarshiSarkar12, I accidentally closed yesterdays PR, so had to open a new one. I  have made the changes as requested.

2023-01-02 08:53 UTC, SaptarshiSarkar12 commented
@bharathkalyans Please create a GitHub issue describing the changes that you want to make and link that with this PR.

2023-01-02 08:56 UTC, SaptarshiSarkar12 commented
I shall review it tomorrow. @bharathkalyans . Let me know when you have made the issue.

2023-01-02 10:05 UTC, bharathkalyans commented
- This PR resolves #194

2023-01-02 10:06 UTC, bharathkalyans commented
Created the issue and linked to it.

2023-01-02 14:23 UTC, SaptarshiSarkar12 commented
> Created the issue and linked to it.

Great @bharathkalyans :+1: ! Shall review it tomorrow.

2023-01-03 06:29 UTC, bharathkalyans commented
The codebase still needs a lot of refactoring, renaming of the Class variables and stuff like that.Will look into it I once I am free!

2023-01-03 07:29 UTC, SaptarshiSarkar12 requested changes
@bharathkalyans Please make the requested changes and then, I shall approve this PR.

2023-01-03 08:14 UTC, SaptarshiSarkar12 commented
> The codebase still needs a lot of refactoring, renaming of the Class variables and stuff like that.Will look into it I once I am free!

That's great. You may do so.

2023-01-03 12:41 UTC, bharathkalyans commented on src/CheckDirectory.java
> +     *
Do you want me to remove these extra comments ?

2023-01-03 12:42 UTC, bharathkalyans commented on src/CheckDirectory.java
> +     *
Do you want me to remove these extra comments ?

2023-01-03 12:43 UTC, bharathkalyans commented on src/CheckDirectory.java
> +     *
Can you be a bit more specific!

2023-01-03 13:12 UTC, SaptarshiSarkar12 commented on src/CheckDirectory.java
> +     *
Yes @bharathkalyans .

2023-01-03 13:13 UTC, SaptarshiSarkar12 commented on src/CheckDirectory.java
> +     *
You can directly click on `commit suggestion` button if there is a monor change.

2023-01-03 14:35 UTC, bharathkalyans commented
> @bharathkalyans Please make the requested changes and then, I shall approve this PR.

Done with the changes 👍🏼

2023-01-04 07:59 UTC, SaptarshiSarkar12 commented
> > @bharathkalyans Please make the requested changes and then, I shall approve this PR.
> 
> Done with the changes 👍🏼

Great!

2023-01-04 08:03 UTC, SaptarshiSarkar12 approved these changes
Looks good to merge :+1: 
Thanks for contributing :rocket: :rocket: :rocket: !!
**@bharathkalyans If you liked contributing to the project, please leave a star :star: . You may join our Discord server for the project's discussions - https://discord.gg/DeT4jXPfkG**

2023-01-04 08:04 UTC, merged