Added code to Display Limited Users for "Be a part of Drifty Family!
SaptarshiSarkar12/Drifty pull request #253
Opened 2023-08-24 07:59 UTC by PriyansuMaurya

" section.

## Fixes issue
#252

## Changes proposed

- Added code to Display Limited no of Users for "Be a part of Drifty Family!" section.

- Added Little bit of Responsive improvements in "Be a part of Drifty Family!" section.

## Check List (Check all the applicable boxes) 
- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-08-24 16:34 UTC, SaptarshiSarkar12 requested changes
@PriyansuMaurya I am requesting some changes on the following :
- Please add this animation for **43+** circular icon.

    [Screencast from 2023-08-24 20-29-24.webm](https://github.com/SaptarshiSarkar12/Drifty/assets/105960032/ea5e2968-b067-4d48-81f9-7984e885e2e1)

- Revert the animation changes you have made for the **contribution**, **stars** and **forks** buttons for _**mobile screens**_. Keep the same animation (violet as background colour when the buttons are hovered) for both desktop and mobile screens.
- Increase the size of the **contribution**, **stars** and **forks** buttons for mobile screens.
    ![drifty-e6krvubkg-saptarshisarkar12 vercel app_(Samsung Galaxy S20 Ultra)](https://github.com/SaptarshiSarkar12/Drifty/assets/105960032/b3263cf5-8c2a-4b28-a993-ab0aa8cece82)
- Change the style of the the **contribution**, **stars** and **forks** buttons to `rounded-lg` instead of `rounded-full`.
- For **IPad Mini**, the avatars are about to overlap. Please fix that.   
    ![drifty-e6krvubkg-saptarshisarkar12 vercel app_(iPad Mini)](https://github.com/SaptarshiSarkar12/Drifty/assets/105960032/ace19da0-7aef-4424-a100-98812d116ae8)

2023-08-24 17:23 UTC, SaptarshiSarkar12 requested changes
Please make this changes and let me know when you are done.

2023-08-24 17:23 UTC, SaptarshiSarkar12 commented on Website/app/Contribute.js
> +                        return index < 6 && <a href={item.html_url} key={index}><Image className="rounded-full" width={80} height={80} src={item.avatar_url + ".webp&s=64"} alt={item.login}></Image></
@PriyansuMaurya The dimensions of the fetched GitHub avatar needs to match with the dimension of the container. So, just commit the below change.
```suggestion
                        return index < 6 && <a href={item.html_url} key={index}><Image className="rounded-full" width={80} height={80} src={item.avatar_url + ".webp&s=80"} alt={item.login}></Image></a>
```

2023-08-24 17:23 UTC, SaptarshiSarkar12 commented on Website/app/Contribute.js
> +                <div className="flex flex-cols-3 justify-center xs:gap-7   lg:pl-5 text-lg font-semibold pr-4">
@PriyansuMaurya Change the flex to grid with 3 columns.
```suggestion
                <div className="grid grid-cols-3 justify-center gap-4 pl-3 pr-3 text-lg font-bold w-auto h-auto">
```

2023-08-24 17:43 UTC, PriyansuMaurya commented
@SaptarshiSarkar12, I have made the requested changes.

2023-08-24 18:17 UTC, SaptarshiSarkar12 requested changes
@PriyansuMaurya Please make the buttons to `rounded-lg`.
Also, fix the text overflow in mobile screens : 
![image](https://github.com/SaptarshiSarkar12/Drifty/assets/105960032/d9cbd6fc-866b-4c0b-ad22-a49a849581c5)

2023-08-24 18:19 UTC, SaptarshiSarkar12 commented
@PriyansuMaurya Also, revert the avatars from square to rounded shape as present in your first commit. The circular shape looks good.

2023-08-24 18:21 UTC, SaptarshiSarkar12 requested changes
@PriyansuMaurya Make the view something like this :
![image](https://github.com/SaptarshiSarkar12/Drifty/assets/105960032/3f0c077e-f1d0-4933-81ea-f6176428064c)

2023-08-25 05:16 UTC, SaptarshiSarkar12 requested changes
@PriyansuMaurya Please make the `rounded-lg` type of buttons for all displays and not just for mobile screens.
![image](https://github.com/SaptarshiSarkar12/Drifty/assets/105960032/758a3ac1-697d-47ea-8f98-8f18c8dd5ba8)

2023-08-25 05:38 UTC, SaptarshiSarkar12 requested changes
@PriyansuMaurya Please change all the `class` attributes to `className` attribute.

2023-08-25 05:42 UTC, SaptarshiSarkar12 commented on Website/app/Contribute.js
> +                        <div className="rounded-full h-16 w-16 flex items-center justify-center border-2 md:border-white text-center   hover:text-black xs:transition ease-in-out delay-150 bg-blue-500
@PriyansuMaurya Please commit this below change :
```suggestion
                        <div className="rounded-full h-20 w-20 text-xl font-semibold flex items-center justify-center border-2 md:border-white text-center   hover:text-black xs:transition ease-in-out delay-150 bg-blue-500 hover:-translate-y-1 hover:scale-110 hover:bg-indigo-500 duration-300">
```

2023-08-25 05:43 UTC, SaptarshiSarkar12 commented on Website/app/Contribute.js
> +                        return index < 6 && <a href={item.html_url} key={index}><Image className="rounded-full" width={64} height={64} src={item.avatar_url + ".webp&s=64"} alt={item.login}></Image></
@PriyansuMaurya Please also commit this changes :
```suggestion
                        return index < 6 && <a href={item.html_url} key={index}><Image className="rounded-full" width={80} height={80} src={item.avatar_url + ".webp&s=80"} alt={item.login}></Image></a>
```

2023-08-25 05:59 UTC, SaptarshiSarkar12 requested changes
@PriyansuMaurya Along with the below changes, please change the `lg:mt-20` attribute in line number 9 to `lg:mt-16`.

2023-08-25 05:59 UTC, SaptarshiSarkar12 commented on Website/app/Contribute.js
> +                <h2 className="text-5xl sm:text-4xl my-12 font-bold lg:mt-20 md:mt-10 sm:pt-10 sm:mb-10 md:pl-20 xs:p-5 xs:text-center" >Be a part of Drifty Family!</h2>
@PriyansuMaurya Please reduce the margin from `20` to `16`.
```suggestion
                <h2 className="text-5xl sm:text-4xl my-12 font-bold lg:mt-16 md:mt-10 sm:pt-10 sm:mb-10 md:pl-20 xs:p-5 xs:text-center" >Be a part of Drifty Family!</h2>
```

2023-08-25 06:04 UTC, SaptarshiSarkar12 requested changes
@PriyansuMaurya Please keep the partially rounded buttons by removing the `md:rounded-full` attribute.

2023-08-25 06:04 UTC, SaptarshiSarkar12 commented on Website/app/Contribute.js
> +                    <a class="rounded-lg md:rounded-full xs:p-2 lg:p-2 lg:w-52 border-2 md:border-white text-center hover:text-black xs:transition ease-in-out delay-150 bg-blue-500 hover:-translate-y
```suggestion
                    <a class="rounded-lg xs:p-2 lg:p-2 lg:w-52 border-2 md:border-white text-center hover:text-black xs:transition ease-in-out delay-150 bg-blue-500 hover:-translate-y-1 hover:scale-110 hover:bg-indigo-500 duration-300" href="https://github.com/SaptarshiSarkar12/Drifty"><i aria-hidden="true" class="fab fa-github pr-1"></i>Contribute</a>
```

2023-08-25 06:04 UTC, SaptarshiSarkar12 commented on Website/app/Contribute.js
> +                    <a class="rounded-lg md:rounded-full xs:p-2 lg:p-2 lg:w-52 border-2 md:border-white text-center hover:text-black xs:transition ease-in-out delay-150 bg-blue-500 hover:-translate-y
```suggestion
                    <a class="rounded-lg xs:p-2 lg:p-2 lg:w-52 border-2 md:border-white text-center hover:text-black xs:transition ease-in-out delay-150 bg-blue-500 hover:-translate-y-1 hover:scale-110 hover:bg-indigo-500 duration-300" href="https://github.com/SaptarshiSarkar12/Drifty/stargazers"><i aria-hidden="true" class="fa fa-regular fa-star pr-1"></i>Stars : 80</a>
```

2023-08-25 06:04 UTC, SaptarshiSarkar12 commented on Website/app/Contribute.js
> +                    <a class="rounded-lg md:rounded-full xs:p-2 lg:p-2 lg:w-52 border-2 md:border-white text-center hover:text-black xs:transition ease-in-out delay-150 bg-blue-500 hover:-translate-y
```suggestion
                    <a class="rounded-lg xs:p-2 lg:p-2 lg:w-52 border-2 md:border-white text-center hover:text-black xs:transition ease-in-out delay-150 bg-blue-500 hover:-translate-y-1 hover:scale-110 hover:bg-indigo-500 duration-300" href="https://github.com/SaptarshiSarkar12/Drifty/network/members"><i aria-hidden="true" class="fa fa-duotone fa-code-fork pr-1"></i>Forks : 77</a>
```

2023-08-25 06:11 UTC, SaptarshiSarkar12 requested changes
@PriyansuMaurya In **IPad Mini**, the GitHub avatars are about to overlap. Can you please add some space/gap between two consecutive avatars (might be `gap-1`) ?
![image](https://github.com/SaptarshiSarkar12/Drifty/assets/105960032/93e64739-300d-4f84-bb51-65a8a013aff8)

2023-08-25 13:49 UTC, PriyansuMaurya commented
After a gap of two attempts, it was still not resolved. Therefore, I had to make changes to achieve what you wanted: 

`width={80} height={80}` => `width={64} height={64}`

If you believe that further changes are necessary, please note that I am not available for them. You can proceed to close this pull request.

2023-08-25 18:21 UTC, SaptarshiSarkar12 commented
> After a `gap-2`, it was still not resolved. Therefore, I had to make changes to achieve what you wanted:
> 
> `width={80} height={80}` => `width={64} height={64}`
> 
> If you believe that further changes are necessary, please note that I am not available for them. You can proceed to close this pull request.

@PriyansuMaurya It is fine if you have changed the image size. Also, no more changes are required for the IPad Mini case. But, there is some small syntactical and some logical changes required.

2023-08-25 18:21 UTC, SaptarshiSarkar12 commented on Website/app/Contribute.js
> +                    <a class="rounded-lg xs:p-2 lg:p-2 lg:w-52 border-2 md:border-white text-center hover:text-black xs:transition ease-in-out delay-150 bg-blue-500 hover:-translate-y-1 hover:scale-1
@PriyansuMaurya Please change `class` to `className` and make the stars and forks dynamically determined as was present previously by committing this suggestion.
 ```suggestion
                <div className="flex flex-cols-3 justify-around items-center xs:gap-7 text-lg font-semibold mx-3">
                    <a className="rounded-lg xs:p-2 lg:p-2 lg:w-52 border-2 md:border-white text-center hover:text-black xs:transition ease-in-out delay-150 bg-blue-500 hover:-translate-y-1 hover:scale-110 hover:bg-indigo-500 duration-300" href="https://github.com/SaptarshiSarkar12/Drifty"><i aria-hidden="true" className="fab fa-github pr-1"></i>Contribute</a>
                    <a className="rounded-lg xs:p-2 lg:p-2 lg:w-52 border-2 md:border-white text-center hover:text-black xs:transition ease-in-out delay-150 bg-blue-500 hover:-translate-y-1 hover:scale-110 hover:bg-indigo-500 duration-300" href="https://github.com/SaptarshiSarkar12/Drifty/stargazers"><i aria-hidden="true" className="fa fa-regular fa-star pr-1"></i>Stars : {values[0]}</a>
                    <a class="rounded-lg xs:p-2 lg:p-2 lg:w-52 border-2 md:border-white text-center hover:text-black xs:transition ease-in-out delay-150 bg-blue-500 hover:-translate-y-1 hover:scale-110 hover:bg-indigo-500 duration-300" href="https://github.com/SaptarshiSarkar12/Drifty/network/members"><i aria-hidden="true" className="fa fa-duotone fa-code-fork pr-1"></i>Forks : {values[1]}</a>
```

2023-08-25 18:29 UTC, SaptarshiSarkar12 approved these changes

2023-08-25 18:29 UTC, SaptarshiSarkar12 approved these changes
@PriyansuMaurya **Looks good to merge 👍.** 
**Thanks for contributing 🚀 🚀.**
You may join our _Discord server_ - **https://discord.gg/DeT4jXPfkG** to get updates about the project.

2023-08-25 18:31 UTC, merged